bind 127.0.0.1
# Substitute manually with your ${REDIS_PASSWORD}
requirepass change_this_to_a_secure_password_123
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
